# Generated by Django 4.0.4 on 2022-05-10 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_chat_pending_user_task_assigned_user_request'),
        ('admins', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task_assigned',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.task'),
        ),
        migrations.AddField(
            model_name='task_assigned',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='task_assigned',
            unique_together={('task', 'user')},
        ),
    ]
