# Generated by Django 4.0.4 on 2022-05-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_attendance_of_user_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.event'),
        ),
        migrations.AlterField(
            model_name='attendance_of_user',
            name='attendance',
            field=models.IntegerField(choices=[(1, 'Present'), (0, 'Absent'), (2, 'Late')], default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('EVT', 'Event'), ('ATD', 'Attendance')], max_length=3),
        ),
        migrations.AlterField(
            model_name='request_feedback',
            name='approval',
            field=models.IntegerField(choices=[(1, 'Accept'), (0, 'Reject'), (2, 'Pending')], default=2),
        ),
    ]
