# Generated by Django 4.0.4 on 2022-05-29 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_report_event_alter_attendance_of_user_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance_of_user',
            name='attendance',
            field=models.IntegerField(choices=[(1, 'Present'), (2, 'Late'), (0, 'Absent')], default=0),
        ),
        migrations.AlterField(
            model_name='request_feedback',
            name='approval',
            field=models.IntegerField(choices=[(0, 'Reject'), (2, 'Pending'), (1, 'Accept')], default=2),
        ),
    ]
