# Generated by Django 4.0.4 on 2022-06-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_event_title_task_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_page', models.CharField(default=None, max_length=30, null=True)),
                ('title_text', models.TextField(default=None, null=True)),
                ('paragraph1', models.TextField(default=None, null=True)),
                ('paragraph2', models.TextField(default=None, null=True)),
                ('paragraph3', models.TextField(default=None, null=True)),
                ('phone_number', models.IntegerField(default=None, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('top_background', models.ImageField(default=None, null=True, upload_to='page')),
                ('image', models.ImageField(default=None, null=True, upload_to='page')),
            ],
        ),
        migrations.AlterField(
            model_name='attendance_of_user',
            name='attendance',
            field=models.IntegerField(choices=[(2, 'Late'), (1, 'Present'), (0, 'Absent')], default=0),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
