# Generated by Django 4.0.4 on 2022-05-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_of_user',
            name='attendance',
            field=models.IntegerField(choices=[(0, 'Absent'), (2, 'Late'), (1, 'Present')], default=0),
        ),
        migrations.AlterField(
            model_name='request_feedback',
            name='approval',
            field=models.IntegerField(choices=[(0, 'Reject'), (2, 'Pending'), (1, 'Accept')], default=2),
        ),
    ]
