# Generated by Django 4.0.4 on 2022-06-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_page_alter_attendance_of_user_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='about_us',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_of_user',
            name='attendance',
            field=models.IntegerField(choices=[(0, 'Absent'), (2, 'Late'), (1, 'Present')], default=0),
        ),
        migrations.AlterField(
            model_name='request_feedback',
            name='approval',
            field=models.IntegerField(choices=[(2, 'Pending'), (0, 'Reject'), (1, 'Accept')], default=2),
        ),
    ]
